### ISSUE TITLE
exporting more than 500 records

### ISSUE THREAD

**Issue by pjmelling** [railsware/highrise_assist#1]
It seems that there might be some limit imposed, perhaps on the Highrise side, that restricts the number of records exported to 500 maximum. Is this true? Is there a right way to get all my records using this tool?

**Comment by kevinashworth** [comment]
Seems the case. Trying to figure out for sure....

**Comment by heaven** [comment]
https://github.com/railsware/highrise_assist/pull/4 solves this problem.

**Comment by pjmelling** [comment]
resolved here https://github.com/railsware/highrise_assist/pull/4
